In [25]:
import numpy as np
import pandas as pd

In [26]:
df = pd.read_csv("/Users/nilesh/Encode_file.csv")

In [27]:
df

   age  Gender     bmi Dibetes     region
0   19    male  27.900     yes  southwest
1   18  female  33.770      no  southeast
2   28    male  33.000      no  southeast
3   33    male  22.705     yes  northwest
4   32    male  28.880      no  northwest
5   31  female  25.740      no  southeast
6   46  female  33.440     yes  southeast
7   37  female  27.740      no  northwest
8   37    male  29.830      no  northeast
9   60  female  25.840      no   northest

In [28]:
df.dtypes

age          int64
Gender      object
bmi        float64
Dibetes     object
region      object
dtype: object

In [29]:
df[['Gender','Dibetes']] = df[['Gender','Dibetes']].astype('category')

In [30]:
df['region'] = df['region'].astype('category')

In [31]:
#df['region'] = df['region'].cat.codes

In [32]:
df.dtypes

age           int64
Gender     category
bmi         float64
Dibetes    category
region     category
dtype: object

In [33]:
df['Gender'] = df['Gender'].cat.codes
df['Dibetes'] = df['Dibetes'].cat.codes

In [34]:
df

   age  Gender     bmi  Dibetes     region
0   19       1  27.900        1  southwest
1   18       0  33.770        0  southeast
2   28       1  33.000        0  southeast
3   33       1  22.705        1  northwest
4   32       1  28.880        0  northwest
5   31       0  25.740        0  southeast
6   46       0  33.440        1  southeast
7   37       0  27.740        0  northwest
8   37       1  29.830        0  northeast
9   60       0  25.840        0   northest

In [35]:
df = pd.get_dummies(df,columns=['region'])

In [36]:
df

,age,Gender,bmi,Dibetes,region_northeast,region_northest,region_northwest,region_southeast,region_southwest
0,19,1,27.900,1,0,0,0,0,1
1,18,0,33.770,0,0,0,0,1,0
2,28,1,33.000,0,0,0,0,1,0
3,33,1,22.705,1,0,0,1,0,0
4,32,1,28.880,0,0,0,1,0,0
5,31,0,25.740,0,0,0,0,1,0
6,46,0,33.440,1,0,0,0,1,0
7,37,0,27.740,0,0,0,1,0,0
8,37,1,29.830,0,1,0,0,0,0
9,60,0,25.840,0,0,1,0,0,0

In [37]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /anaconda3/lib/python3.7/site-packages (2.1.0)
Requirement already satisfied: patsy>=0.4.1 in /anaconda3/lib/python3.7/site-packages (from category_encoders) (0.5.0)
Requirement already satisfied: pandas>=0.21.1 in /anaconda3/lib/python3.7/site-packages (from category_encoders) (0.23.4)
Requirement already satisfied: numpy>=1.11.3 in /anaconda3/lib/python3.7/site-packages (from category_encoders) (1.15.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /anaconda3/lib/python3.7/site-packages (from category_encoders) (0.22.1)
Requirement already satisfied: scipy>=0.19.0 in /anaconda3/lib/python3.7/site-packages (from category_encoders) (1.1.0)
Requirement already satisfied: statsmodels>=0.6.1 in /anaconda3/lib/python3.7/site-packages (from category_encoders) (0.9.0)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from patsy>=0.4.1->category_encoders) (1.11.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /anaconda3/lib/python3.7/site-packages (from pandas>=0.21.1->category_encoders) (2.7.3)
Requirement already satisfied: pytz>=2011k in /anaconda3/lib/python3.7/site-packages (from pandas>=0.21.1->category_encoders) (2018.5)
Requirement already satisfied: joblib>=0.11 in /anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.20.0->category_encoders) (0.14.1)
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [38]:
import category_encoders as ce

In [39]:
dfbin = df.copy()

In [40]:
bincode = ce.BinaryEncoder(dfbin,cols=['Gender','Dibetes','region'])

In [41]:
df_bin = bincode.fit_transform(dfbin)

KeyError: 'region'

In [ ]:
df_bin.head(100)